cat_dist_map = {'access gateway': 1.0,
 'adventure sports venue': 1,
 'agriculture business': 0.5,
 'airport': 1,
 'amusement park': 1,
 'automotive dealer': 0.5,
 'bank': 0.5,
 'beach': 1.0,
 'business park': 1.0,
 'cafpub': 0.5,
 'cafépub': 0.5,
 'camping ground': 1.0,
 'car wash': 0.5,
 'cash dispenser': 0.2,
 'casino': 1.0,
 'cinema': 1.0,
 'club association': 0.5,
 'collegeuniversity': 1.0,
 'commercial building': 0.5,
 'community center': 1,
 'company': 0.5,
 'courier drop box': 0.2,
 'courthouse': 1,
 'cultural center': 1,
 'dentist': 0.5,
 'department store': 0.5,
 'doctor': 0.5,
 'embassy': 1.0,
 'emergency medical service': 0.5,
 'emergency room': 0.5,
 'entertainment': 1.0,
 'exchange': 0.5,
 'exhibition convention center': 1.0,
 'fire stationbrigade': 1,
 'geographic feature': 1.0,
 'golf course': 1.0,
 'government office': 0.5,
 'health care service': 0.5,
 'helipadhelicopter landing': 1.0,
 'holiday rental': 0.5,
 'hospitalpolyclinic': 0.5,
 'hotelmotel': 0.5,
 'ice skating rink': 1.0,
 'important tourist attraction': 1,
 'industrial building': 0.5,
 'leisure center': 1.0,
 'library': 1,
 'manufacturing facility': 0.5,
 'marina': 1.0,
 'market': 0.5,
 'media facility': 0.5,
 'military installation': 1.0,
 'motoring organization office': 0.5,
 'museum': 1.0,
 'native reservation': 1.0,
 'nightlife': 0.5,
 'non governmental organization': 0.5,
 'open parking area': 0.5,
 'park and recreation area': 1.0,
 'parking garage': 0.5,
 'petrol station': 0.5,
 'pharmacy': 0.5,
 'place of worship': 1.0,
 'police station': 1.0,
 'portwarehouse facility':0.5,
 'post office': 1.0,
 'primary resourceutility': 0.5,
 'prisoncorrectional facility': 1,
 'public amenity': 0.5,
 'public transport stop': 0.5,
 'railway station': 1.0,
 'rentacar facility': 0.5,
 'rentacar parking': 0.5,
 'repair facility': 0.5,
 'research facility': 0.5,
 'residential accommodation': 0.5,
 'rest area': 0.5,
 'restaurant': 0.5,
 'restaurant area': 0.5,
 'scenicpanoramic view': 1,
 'school': 0.5,
 'shop': 0.5,
 'shopping center': 0.5,
 'sports center': 0.5,
 'stadium': 1.0,
 'swimming pool': 1.0,
 'tennis court': 0.5,
 'theater':0.5,
 'tourist information office': 0.5,
 'traffic service center': 1,
 'trail system': 1.0,
 'transport authorityvehicle registration': 1,
 'truck stop': 1,
 'veterinarian': 0.5,
 'water sport': 1,
 'weigh station': 0.5,
 'welfare organization': 0.5,
 'winery': 1,
 'zoo arboreta botanical garden': 1}